project 'Bizintu.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
target 'Bizintu' do
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Firebase/Messaging'
pod 'Firebase/Database'
pod 'Firebase/Invites'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Crash'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'GoogleSignIn'
pod 'FacebookCore'
pod 'FacebookLogin'
use_frameworks!
pod 'TwitterKit'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
end
